import SwiftUI

enum Lang: String, CaseIterable, Identifiable {
    case zh, en
    var id: String { rawValue }
    var label: String { self == .zh ? "中文" : "English" }
}

/// Lightweight in-app localization so the language can be toggled live
/// (mock UI – avoids bundle/.strings reload friction). Covers chrome only;
/// sample chat content stays as-is per the design.
final class Localization: ObservableObject {
    @AppStorage("flow.lang") private var stored: String = "zh"
    @Published var lang: Lang = .zh

    init() { lang = Lang(rawValue: stored) ?? .zh }

    func set(_ l: Lang) { lang = l; stored = l.rawValue }

    func t(_ key: String) -> String { Self.table[key]?[lang] ?? key }

    private static let table: [String: [Lang: String]] = [
        // App / nav
        "app.name":        [.zh: "流动", .en: "FLOW"],
        "nav.chats":       [.zh: "聊天", .en: "Chats"],
        "nav.companions":  [.zh: "搭子", .en: "AI"],
        "nav.groups":      [.zh: "群组", .en: "Groups"],
        "nav.discover":    [.zh: "发现", .en: "Discover"],
        "nav.profile":     [.zh: "我",   .en: "Profile"],
        "nav.settings":    [.zh: "设置", .en: "Settings"],
        // Chats
        "chats.title":     [.zh: "我的聊天", .en: "My Chats"],
        "chats.empty":     [.zh: "还没有会话，去发现/群组里开始聊天吧", .en: "No chats yet — start one from Discover/Groups"],
        "groups.friendEmpty":[.zh: "还没有好友群，点 + 拉好友建群", .en: "No friend groups — tap + to create one"],
        "new.chat":        [.zh: "发起聊天", .en: "New chat"],
        "new.group":       [.zh: "创建群聊", .en: "New group"],
        "conv.members":    [.zh: "位成员", .en: "members"],
        "conv.addAI":      [.zh: "加入 AI 搭子", .en: "Add AI companion"],
        "conv.summon":     [.zh: "让", .en: "Ask "],
        "conv.summarize":  [.zh: "总结群聊", .en: "Summarize"],
        "conv.smartReply": [.zh: "智能回复", .en: "Smart reply"],
        "conv.summary":    [.zh: "群聊总结", .en: "Summary"],
        "conv.shareCompanion":[.zh: "分享搭子名片", .en: "Share companion"],
        "conv.members.manage":[.zh: "群成员", .en: "Members"],
        "conv.leave":      [.zh: "退出群聊", .en: "Leave group"],
        "moments.addPhoto":[.zh: "加图片", .en: "Add photo"],
        "moments.uploading":[.zh: "上传中…", .en: "Uploading…"],
        "moments.post":    [.zh: "发动态", .en: "New post"],
        "moments.send":    [.zh: "发布", .en: "Send"],
        "moments.empty":   [.zh: "还没有动态，发一条吧", .en: "No posts yet — share something"],
        "moments.comments":[.zh: "评论", .en: "Comments"],
        "moments.commentHint":[.zh: "写评论…", .en: "Write a comment…"],
        "profile.message": [.zh: "发消息", .en: "Message"],
        "profile.edit":    [.zh: "编辑资料", .en: "Edit profile"],
        "profile.save":    [.zh: "保存", .en: "Save"],
        "profile.nickname":[.zh: "昵称", .en: "Nickname"],
        "profile.signature":[.zh: "个性签名", .en: "Signature"],
        "profile.companions":[.zh: "TA 的公开搭子", .en: "Public companions"],
        "friends.title":    [.zh: "好友", .en: "Friends"],
        "friends.add":      [.zh: "添加好友", .en: "Add Friend"],
        "friends.requests": [.zh: "好友申请", .en: "Friend Requests"],
        "friends.empty":    [.zh: "还没有好友，点右上角添加", .en: "No friends yet — tap + to add"],
        "friends.searchHint":[.zh: "按昵称或邮箱搜索", .en: "Search by name or email"],
        "friend.add":       [.zh: "加好友", .en: "Add"],
        "friend.pending":   [.zh: "已申请", .en: "Pending"],
        "friend.isFriend":  [.zh: "已是好友", .en: "Friends"],
        "friend.accept":    [.zh: "同意", .en: "Accept"],
        "chats.preview":   [.zh: "最近一条消息预览…", .en: "Last message preview."],
        "status.online":   [.zh: "在线", .en: "Online"],
        "status.offline":  [.zh: "离线", .en: "Offline"],
        "chat.today":      [.zh: "今天", .en: "Today"],
        "chat.placeholder":[.zh: "输入消息…", .en: "Type a message…"],
        "chat.send":       [.zh: "发送", .en: "SEND"],
        "chat.voice":      [.zh: "语音", .en: "Text"],
        // Groups
        "groups.title":    [.zh: "群组", .en: "Groups"],
        "groups.create":   [.zh: "创建新群组", .en: "Create Group"],
        "groups.name":     [.zh: "群组名称", .en: "Group name"],
        "groups.members":  [.zh: "选择成员", .en: "Select members"],
        "groups.confirm":  [.zh: "创建", .en: "Create"],
        // Discover
        "discover.title":  [.zh: "发现", .en: "Discover"],
        "discover.elite":  [.zh: "精英服务", .en: "Elite Services"],
        "discover.join":   [.zh: "加入", .en: "JOIN"],
        // 发现三栏
        "disc.market":     [.zh: "搭子市场", .en: "Market"],
        "disc.groups":     [.zh: "社群广场", .en: "Communities"],
        "disc.moments":    [.zh: "朋友圈", .en: "Moments"],
        "disc.soon":       [.zh: "即将上线", .en: "Coming soon"],
        // 社群广场
        "group.create":    [.zh: "创建社群", .en: "New community"],
        "group.byCode":    [.zh: "邀请码加入", .en: "Join by code"],
        "group.codeHint":  [.zh: "输入 6 位邀请码", .en: "6-char invite code"],
        "group.join":      [.zh: "加入", .en: "Join"],
        "group.apply":     [.zh: "申请加入", .en: "Apply"],
        "group.joined":    [.zh: "已加入", .en: "Joined"],
        "group.pending":   [.zh: "待审核", .en: "Pending"],
        "group.needCode":  [.zh: "需邀请码", .en: "Code only"],
        "group.joinedToast":[.zh: "已加入 ", .en: "Joined "],
        "group.appliedToast":[.zh: "已提交申请，等群主通过", .en: "Request sent, awaiting approval"],
        "group.codeInvalid":[.zh: "邀请码无效", .en: "Invalid code"],
        "group.mode.open": [.zh: "开放加入", .en: "Open"],
        "group.mode.code": [.zh: "邀请码", .en: "Code"],
        "group.mode.approval":[.zh: "需审批", .en: "Approval"],
        "group.name":      [.zh: "社群名称", .en: "Community name"],
        "group.desc":      [.zh: "社群简介", .en: "Description"],
        "group.joinMode":  [.zh: "加入方式", .en: "Join mode"],
        "group.cap":       [.zh: "人数上限", .en: "Member cap"],
        "group.createCta": [.zh: "创建", .en: "Create"],
        "common.cancel":   [.zh: "取消", .en: "Cancel"],
        // 群组 Tab 分段 + 社群详情
        "groups.seg.groups":      [.zh: "群组", .en: "Groups"],
        "groups.seg.communities": [.zh: "社群", .en: "Communities"],
        "community.members":   [.zh: "成员", .en: "Members"],
        "community.owner":     [.zh: "群主", .en: "Owner"],
        "community.codeOnly":  [.zh: "该社群需邀请码加入", .en: "This community is invite-code only"],
        "community.mineEmpty": [.zh: "还没加入任何社群，去发现逛逛", .en: "No communities yet — explore in Discover"],
        // 认领市场
        "market.title":    [.zh: "搭子市场", .en: "Companion Market"],
        "market.subtitle": [.zh: "认领别人养成的 AI 搭子，连记忆一起", .en: "Adopt others' AI companions — memories included"],
        "market.empty":    [.zh: "还没有发布的搭子", .en: "No published companions yet"],
        "market.by":       [.zh: "来自 ", .en: "by "],
        "market.gen":      [.zh: "第", .en: "Gen "],
        "market.genUnit":  [.zh: " 代传承", .en: " gen"],
        "market.lineage":  [.zh: "传承第 ", .en: "Lineage gen "],
        "market.memories": [.zh: "TA 公开的记忆", .en: "Shared memories"],
        "market.hiddenA":  [.zh: "还有 ", .en: "+"],
        "market.hiddenB":  [.zh: " 段回忆，认领后聊天慢慢发现", .en: " more — discover them by chatting after adopting"],
        "market.adopt":    [.zh: "认领", .en: "Adopt"],
        "market.adopted":  [.zh: "已认领 🎉", .en: "Adopted 🎉"],
        "market.adoptNote":[.zh: "认领后会成为你的搭子，继承这些记忆；你可以继续养它、再发布", .en: "It becomes yours with these memories; keep raising it and re-publish"],
        // 发布
        "publish.menu":    [.zh: "发布到市场", .en: "Publish to market"],
        "publish.title":   [.zh: "发布到搭子市场", .en: "Publish companion"],
        "publish.subtitle":[.zh: "勾选要公开的记忆，别人认领后能看到", .en: "Pick memories to share with adopters"],
        "publish.noMem":   [.zh: "暂无记忆，将只发布人设", .en: "No memories — persona only"],
        "publish.cta":     [.zh: "发布", .en: "Publish"],
        "publish.share":   [.zh: "公开", .en: "share "],
        "publish.done":    [.zh: "已发布 🎉", .en: "Published 🎉"],
        "publish.shared":  [.zh: "公开", .en: "Shared"],
        "publish.private": [.zh: "私密", .en: "Private"],
        "publish.privacyNote":[.zh: "私密记忆永不分享。请勿公开他人隐私。", .en: "Private memories are never shared. Don't expose others' privacy."],
        // Settings
        "settings.title":     [.zh: "设置", .en: "Settings"],
        "settings.switched":  [.zh: "流动模式", .en: "Switched mode"],
        "settings.clash":     [.zh: "冲突模式", .en: "Clash Mode"],
        "settings.sliders":   [.zh: "滑块", .en: "Sliders"],
        "settings.scheme":    [.zh: "滑块配色", .en: "Sliders scheme"],
        "settings.selected":  [.zh: "选择配色", .en: "Selected scheme"],
        "settings.language":  [.zh: "语言", .en: "Language"],
        "settings.colorDepth":[.zh: "配色深浅", .en: "Color depth"],
        "settings.appearance":[.zh: "外观", .en: "Appearance"],
        "appearance.system":  [.zh: "跟随系统", .en: "System"],
        "appearance.light":   [.zh: "浅色", .en: "Light"],
        "appearance.dark":    [.zh: "深色", .en: "Dark"],
        "settings.clearCache":[.zh: "清除缓存", .en: "Clear cache"],
        "settings.cacheCleared":[.zh: "缓存已清除", .en: "Cache cleared"],
        // Profile / contact
        "profile.title":   [.zh: "个人资料", .en: "Profile"],
        "profile.company": [.zh: "团队公司", .en: "Company of Teams"],
        "profile.edit":    [.zh: "编辑", .en: "Edit"],
        // Footer
        "footer.connectivity": [.zh: "已连接", .en: "Connected"],
        "footer.quick":        [.zh: "快捷访问", .en: "Quick access"],
        "footer.quickAI":      [.zh: "问 AI", .en: "Ask AI"],
        "quick.aiName":        [.zh: "FLOW 助手", .en: "FLOW Assistant"],
        "quick.aiGreeting":    [.zh: "嗨，我是 FLOW 助手，有什么可以帮你？", .en: "Hi! I'm the FLOW assistant. How can I help?"],
        "search.placeholder":  [.zh: "搜索", .en: "Search"],
        // Auth
        "auth.login":        [.zh: "登录", .en: "Log in"],
        "auth.register":     [.zh: "注册", .en: "Sign up"],
        "auth.email":        [.zh: "邮箱", .en: "Email"],
        "auth.password":     [.zh: "密码", .en: "Password"],
        "auth.nickname":     [.zh: "昵称", .en: "Nickname"],
        "auth.welcome":      [.zh: "欢迎回来", .en: "Welcome back"],
        "auth.createAccount":[.zh: "创建账号", .en: "Create account"],
        "auth.toRegister":   [.zh: "还没有账号？去注册", .en: "No account? Sign up"],
        "auth.toLogin":      [.zh: "已有账号？去登录", .en: "Have an account? Log in"],
        "auth.tagline":      [.zh: "AI 驱动的聊天", .en: "AI-powered chat"],
        "auth.logout":       [.zh: "退出登录", .en: "Log out"],
        "auth.account":      [.zh: "账号", .en: "Account"],
        "auth.member.free":  [.zh: "免费版", .en: "Free"],
        "auth.member.pro":   [.zh: "会员", .en: "Pro"],
        // Paywall / 会员
        "paywall.title":     [.zh: "升级会员", .en: "Go Pro"],
        "paywall.subtitle":  [.zh: "解锁更强的 AI 体验", .en: "Unlock a smarter AI"],
        "paywall.cta":       [.zh: "立即开通", .en: "Subscribe"],
        "paywall.buying":    [.zh: "开通中…", .en: "Processing…"],
        "paywall.restore":   [.zh: "恢复购买", .en: "Restore"],
        "paywall.note":      [.zh: "演示版：点击直接升级（未接真实支付）", .en: "Demo: upgrades instantly (no real payment)"],
        "paywall.success":   [.zh: "已开通会员 🎉", .en: "You're Pro now 🎉"],
        "paywall.perMonth":  [.zh: "元/月", .en: " /mo"],
        "paywall.perYear":   [.zh: "元/年", .en: " /yr"],
        "membership.upgrade":[.zh: "升级会员", .en: "Upgrade"],
        "membership.expiry": [.zh: "到期", .en: "Expires"],
        "cap.title":         [.zh: "今日次数已用完", .en: "Daily limit reached"],
        // AI chat
        "chat.aiThinking":   [.zh: "正在输入…", .en: "typing…"],
        // 消息操作
        "msg.copy":          [.zh: "复制", .en: "Copy"],
        "msg.quote":         [.zh: "引用", .en: "Quote"],
        "msg.delete":        [.zh: "删除", .en: "Delete"],
        "msg.recall":        [.zh: "撤回", .en: "Unsend"],
        "msg.recalled":      [.zh: "已撤回", .en: "Recalled"],
        "chat.mute":         [.zh: "消息免打扰", .en: "Mute"],
        "chat.unmute":       [.zh: "取消免打扰", .en: "Unmute"],
        "chat.muted":        [.zh: "已开启免打扰", .en: "Muted"],
        "chat.unmuted":      [.zh: "已取消免打扰", .en: "Unmuted"],
        "chat.clear":        [.zh: "清空聊天记录", .en: "Clear chat"],
        "chat.clearConfirm": [.zh: "确定清空本会话的聊天记录？", .en: "Clear all messages in this chat?"],
        "chat.cleared":      [.zh: "已清空", .en: "Cleared"],
        "chat.photo":        [.zh: "照片", .en: "Photo"],
        "chat.file":         [.zh: "文件", .en: "File"],
        // Companions
        "companions.title":    [.zh: "AI 搭子", .en: "AI Companions"],
        "companions.subtitle": [.zh: "找个 AI 聊聊，它会记住你", .en: "Chat with an AI that remembers you"],
        "companions.create":   [.zh: "创建搭子", .en: "New companion"],
        "companion.delete":    [.zh: "删除搭子", .en: "Delete"],
        "companion.memoryCount":[.zh: "记忆 ", .en: "memories: "],
        "companion.name":      [.zh: "名字", .en: "Name"],
        "companion.persona":   [.zh: "人设（它是谁、怎么说话）", .en: "Persona (who it is, how it talks)"],
        "companion.greeting":  [.zh: "开场白（可选）", .en: "Greeting (optional)"],
        "companion.tint":      [.zh: "配色", .en: "Color"],
        "companion.save":      [.zh: "创建", .en: "Create"],
        // 记忆
        "msg.remember":        [.zh: "记住这个", .en: "Remember this"],
        "msg.remembered":      [.zh: "已记住", .en: "Remembered"],
        "chat.memories":       [.zh: "查看记忆", .en: "Memories"],
        "memories.title":      [.zh: "记忆", .en: "Memories"],
        "memories.subtitle":   [.zh: " 记得关于你的事", .en: " remembers about you"],
        "memories.empty":      [.zh: "还没有记忆，聊几句它就开始记住你", .en: "No memories yet — chat and it'll start remembering"],
        "memories.addHint":    [.zh: "手动添加一条记忆…", .en: "Add a memory…"],
        "memories.add":        [.zh: "添加", .en: "Add"],
        "memories.from":       [.zh: "传承自 ", .en: "from "],
        // AI 助手（输入栏）
        "assist.rewrite":      [.zh: "润色语气", .en: "Rewrite tone"],
        "assist.translate":    [.zh: "翻译 中⇄英", .en: "Translate"],
        "assist.suggest":      [.zh: "回复建议", .en: "Suggest replies"],
        "assist.sticker":      [.zh: "生成贴纸", .en: "Make sticker"],
        "assist.stickerCtx":   [.zh: "按当前聊天语境生成", .en: "Generate from chat context"],
        "assist.working":      [.zh: "AI 处理中…", .en: "Working…"],
        // 表情包面板
        "sticker.panel":       [.zh: "表情包", .en: "Stickers"],
        "sticker.recent":      [.zh: "最近", .en: "Recent"],
        "sticker.favorites":   [.zh: "收藏", .en: "Favorites"],
        "sticker.make":        [.zh: "生成新贴纸", .en: "New sticker"],
        "sticker.makeHint":    [.zh: "描述你想要的贴纸…", .en: "Describe a sticker…"],
        "sticker.empty":       [.zh: "还没有贴纸，生成一个吧", .en: "No stickers yet — make one"],
        "sticker.saved":       [.zh: "已存到表情包", .en: "Saved to stickers"],
        "sticker.autoSetting": [.zh: "生成贴纸后自动发送到会话", .en: "Auto-send new stickers"],
        "sticker.send":        [.zh: "发送", .en: "Send"],
        "sticker.preview":     [.zh: "预览贴纸", .en: "Preview"],
        "sticker.discard":     [.zh: "丢弃", .en: "Discard"],
        "sticker.autoRemember":[.zh: "以后自动发送，不再询问", .en: "Always send, don't ask again"],
        "sticker.favDrawer":   [.zh: "收藏的表情包", .en: "Favorite stickers"],
        "sticker.favEmpty":    [.zh: "还没有收藏\n去「个人信息 → 我的表情包」点星收藏", .en: "No favorites yet\nStar some in Profile → My Stickers"],
        "sticker.libraryHint": [.zh: "点星收藏，收藏的会出现在聊天表情包里", .en: "Star to favorite — favorites show in chat"],
        "profile.stickers":    [.zh: "我的表情包", .en: "My Stickers"],
        "tone.natural":        [.zh: "自然", .en: "Natural"],
        "tone.serious":        [.zh: "正经", .en: "Formal"],
        "tone.funny":          [.zh: "幽默", .en: "Funny"],
        "tone.gentle":         [.zh: "委婉", .en: "Gentle"],
        "tone.professional":   [.zh: "专业", .en: "Professional"],
    ]
}
